fix: correct stdin/stdout/stderr redirection in detach mode
AttributeError: '_io.TextIOWrapper' object has no attribute 'open'

Changed from:
  sys.stdin.open(os.devnull)
To:
  sys.stdin = open(os.devnull, 'r')